version: "3"

services:
  app:
    build: .
    container_name: "blog"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blogdb
    ports:
      - "3307:3306"